on: [push]

jobs:
  newImage:
    runs-on: self-hosted
    name: Update website
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Use the output from the `hello` step
      - name: move to destination
        run: cd /var/www/html/pariscaretaker.fr
      - name: fetch
        run: git fetch
      - name: pull
        run: git pull
